# Generated by Django 4.2.13 on 2024-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_has_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
    ]
