# Generated by Django 4.2.13 on 2024-05-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
    ]
