# Generated by Django 4.2.13 on 2024-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_industry_region_alter_job_type_job_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='status',
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('Дистанційно', 'Дистанційно'), ('На місці', 'На місці'), ('Гібрид', 'Гібрид')], max_length=50, null=True),
        ),
    ]
