# Generated by Django 4.2.13 on 2024-05-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='est_data',
        ),
    ]
