# Generated by Django 4.2.13 on 2024-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_applyjob_status_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('Дистанційно', 'Дистанційно'), ('На місці', 'На місці'), ('Гібрид', 'Гібрид')], max_length=20, null=True),
        ),
    ]
