# Generated by Django 4.2.13 on 2024-05-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_company_user_has_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_company',
        ),
    ]
